# getting base image python 3
FROM python:3

MAINTAINER sunhan pal <11013784@stud.hochschule-heidelberg.de>

WORKDIR /Users/xiaoni/Desktop/11013784-hanSun-assignment-1

COPY paranthesis.py .

CMD ["python", "./paranthesis.py"]
